/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATable: typeof import('ant-design-vue/es')['Table']
    BetterScroll: typeof import('./src/components/BetterScroll.vue')['default']
    Bulletin: typeof import('./src/components/dashboard/Bulletin.vue')['default']
    CkEditor: typeof import('./src/components/ckeditor/CkEditor.vue')['default']
    DraggableCard: typeof import('./src/components/DraggableCard.vue')['default']
    IncomeChart: typeof import('./src/components/dashboard/IncomeChart.vue')['default']
    LzyIcon: typeof import('./src/components/LzyIcon.vue')['default']
    PostsForm: typeof import('./src/components/form/PostsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetAiKey: typeof import('./src/components/webSet/SetAiKey.vue')['default']
    SetFooterOrAi: typeof import('./src/components/webSet/SetFooterOrAi.vue')['default']
    SetLoadGif: typeof import('./src/components/webSet/SetLoadGif.vue')['default']
    SetSystem: typeof import('./src/components/webSet/SetSystem.vue')['default']
    SliderVerificationCode: typeof import('./src/components/SliderVerificationCode.vue')['default']
    StatisticsChart: typeof import('./src/components/dashboard/StatisticsChart.vue')['default']
    TableHeaderOperation: typeof import('./src/components/TableHeaderOperation.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    UpdateLog: typeof import('./src/components/dashboard/UpdateLog.vue')['default']
    UploadLogLeft: typeof import('./src/components/dashboard/UploadLogLeft.vue')['default']
    UserForm: typeof import('./src/components/form/UserForm.vue')['default']
  }
}
